config:
  partial_parse: true
  printer_width: 120
  send_anonymous_usage_stats: false
  use_colors: true
normalize:
  outputs:
    prod:
      dbname: source_analytics
      host: localhost
      pass: secret
      port: 5433
      schema: public
      threads: 32
      type: postgres
      user: postgres
  target: prod