
version: 2

models:
    - name: rental_stats
      description: "Transforms data from raw rental data"
      columns:
          - name: rental_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
